### ISSUE TITLE
BOOST_ASSERT(has_capacity) in the boost/lockfree/queue:179 on Windows

### ISSUE THREAD

**Issue by Tharnum** [henry-ch/asynchronous#4]
Hi!

I tried to execute one of boost::asynchronous examples but got BOOST_ASSERT(has_capacity). Default constructor of the lockfree_queue class is disabled for Microsoft C++ compilers (lockfree_queue.hpp:67-69):
```
#ifndef _MSC_VER
    lockfree_queue():m_queue(16){}
#endif
```
so template constructor is called without arguments:
```
template<typename... Args>
lockfree_queue(Args... args)
```

Without this #ifndef all works fine. What am I doing wrong? :(

**Comment by henry-ch** [comment]
Probably you're not doing anything wrong.
The #ifndef was added because of a MSVC compile error, which may have been fixed by now.
I need to know:
- compiler version
- boost version
- example used

If you're using a current boost version and compiler it means I could remove those, which would be great.

**Comment by Tharnum** [comment]
Oh, sorry.

Compiler: MSVC 2015 Update 3
Boost: 1.64.0
Example: from 'Interrupting tasks' section. Actually any example.

**Comment by henry-ch** [comment]
#ifndef removed. Thanks
